import { CLASSROOM_LEARNING_MODE } from "../../shared/domain/classroomLearningMode";

export const DETAILED_MODE_CONFIGS = [
  {
    id: CLASSROOM_LEARNING_MODE.NEW_LESSON,
    title: "上新课",
    englishTitle: "Learn New Lesson",
    tag: "首学推荐 · 循序渐进",
    tagType: "emerald",
    iconName: "book-open",
    kidEmoji: "🌱",
    kidTitle: "学新课",
    kidMotto: "零基础 · 跟着老师轻松学",
    kidRecommendBadge: "🌟 第一次学选它",
    kidDescription: "跟着微课一步一步学，不用做前测，边听边练轻松搞懂新知识！",
    kidPath: [
      { num: "1", label: "看精讲微课", desc: "图文讲解", icon: "video" },
      { num: "2", label: "随堂互动练", desc: "即学即练", icon: "edit" },
      { num: "3", label: "闯关通关", desc: "点亮星星", icon: "star" },
    ],
    accentColor: "#10b981",
    accentBg: "#ecfdf5",
    accentBorder: "#6ee7b7",
    cardGlow: "rgba(16, 185, 129, 0.18)",
    badgeBg: "#d1fae5",
    badgeFg: "#065f46",
    summary: "不做前测，直接进入新知讲授与即时随堂巩固。",
    suitableFor: "第一次接触这节课的新知识、或者想重新系统学一遍的同学。",
    estimatedDuration: "20 - 30 分钟",
    hasPreAssessment: false,
    preAssessmentLabel: "无需课前小测",
    practicePolicy: "边学边练 · 阶梯式题组",
    steps: [
      {
        index: 1,
        title: "学习新知",
        description: "概念微课与图文精讲，深度拆解核心定义与几何直观。",
      },
      {
        index: 2,
        title: "随堂演练",
        description: "即学即练阶梯题组，即时对错判定与分步智能解析。",
      },
      {
        index: 3,
        title: "掌握检查",
        description: "课末掌握度小测，检验当堂吸收效果并更新知识图谱。",
      },
    ],
    highlights: [
      "零门槛直接开学，消除测试心理负担",
      "精讲与随堂练习穿插，轻松跟上节奏",
      "学完立即点亮掌握度小星星",
    ],
    ctaText: "开启「学新课」之旅",
  },
  {
    id: CLASSROOM_LEARNING_MODE.FOUNDATION,
    title: "打基础",
    englishTitle: "Build Solid Foundation",
    tag: "智能跳关 · 逐层过关",
    tagType: "blue",
    iconName: "layers",
    kidEmoji: "🚀",
    kidTitle: "打基础",
    kidMotto: "测一测 · 智能跳关免重复",
    kidRecommendBadge: "⚡ 课后巩固推荐",
    kidDescription: "先做5道题摸底，已经学会的自动跳过，只练不熟的关卡，超级省时！",
    kidPath: [
      { num: "1", label: "5道题小测", desc: "快速摸底", icon: "zap" },
      { num: "2", label: "智能跳过", desc: "学会免练", icon: "skip" },
      { num: "3", label: "闯关升级", desc: "专攻弱关", icon: "award" },
    ],
    accentColor: "#3b82f6",
    accentBg: "#eff6ff",
    accentBorder: "#93c5fd",
    cardGlow: "rgba(59, 130, 246, 0.18)",
    badgeBg: "#dbeafe",
    badgeFg: "#1e40af",
    summary: "先做课前测摸底学情，按认知层级逐层学习并解锁。",
    suitableFor: "上完课后做练习、想查漏补缺快速过关的同学。",
    estimatedDuration: "15 - 25 分钟",
    hasPreAssessment: true,
    preAssessmentLabel: "含 5-8 题摸底小测",
    practicePolicy: "智能跳关 · 认知层级突破",
    steps: [
      {
        index: 1,
        title: "课前小测",
        description: "精选5-8道小题摸底已知水平，快速识别掌握与薄弱点。",
      },
      {
        index: 2,
        title: "逐层学习",
        description: "已掌握点自动跳关免学，集中精力攻克未达标难点层级。",
      },
      {
        index: 3,
        title: "解锁进阶",
        description: "层级递进闯关，稳扎稳打夯实知识底座，解锁进阶内容。",
      },
    ],
    highlights: [
      "会做的题目自动跳过，不浪费一分钟",
      "关卡循序渐进，像闯关游戏一样升级",
      "专攻易错点，稳步夯实基础知识",
    ],
    ctaText: "开启「打基础」挑战",
  },
  {
    id: CLASSROOM_LEARNING_MODE.REMEDIATION,
    title: "查缺补漏",
    englishTitle: "Targeted Remediation",
    tag: "综合诊断 · 靶向拔高",
    tagType: "amber",
    iconName: "scan-search",
    kidEmoji: "🎯",
    kidTitle: "查缺补漏",
    kidMotto: "瞄准弱点 · 消灭错题冲满分",
    kidRecommendBadge: "🏆 考前冲刺必备",
    kidDescription: "做一次考点大扫描，找出所有薄弱失分点，看针对微课逐一消灭！",
    kidPath: [
      { num: "1", label: "考点大体检", desc: "全卷测验", icon: "search" },
      { num: "2", label: "定位失分点", desc: "诊断雷达", icon: "target" },
      { num: "3", label: "消灭薄弱项", desc: "拔高冲刺", icon: "shield" },
    ],
    accentColor: "#f59e0b",
    accentBg: "#fffbeb",
    accentBorder: "#fcd34d",
    cardGlow: "rgba(245, 158, 11, 0.2)",
    badgeBg: "#fef3c7",
    badgeFg: "#92400e",
    summary: "先做单元综合测试，智能诊断弱项并逐个攻克。",
    suitableFor: "单元复习、期中/期末考前冲刺、想要重点消灭错题弱项的同学。",
    estimatedDuration: "30 - 45 分钟",
    hasPreAssessment: true,
    preAssessmentLabel: "包含单元综合测评",
    practicePolicy: "弱项雷达 · 靶向变式题集",
    steps: [
      {
        index: 1,
        title: "单元测试",
        description: "全卷综合测评扫描本单元全部考点，快速定位薄弱环节。",
      },
      {
        index: 2,
        title: "定位薄弱点",
        description: "系统生成弱项诊断雷达图，清晰呈现知识切片掌握度短板。",
      },
      {
        index: 3,
        title: "逐点靶向攻克",
        description: "针对错题知识点点拨微课，搭配同类变式题强化刷透。",
      },
    ],
    highlights: [
      "一键扫描单元考点盲区，拒绝盲目刷题",
      "针对性点拨微课，讲透易错陷阱",
      "同类好题趁热打铁，确保真正掌握",
    ],
    ctaText: "开启「查缺补漏」冲刺",
  },
];
