import { CLASSROOM_LEARNING_MODE } from "../../shared/domain/classroomLearningMode";

export const DETAILED_MODE_CONFIGS = [
  {
    id: CLASSROOM_LEARNING_MODE.NEW_LESSON,
    title: "上新课",
    englishTitle: "Learn New Lesson",
    tag: "首学推荐 · 循序渐进",
    tagType: "emerald",
    iconName: "book-open",
    accentColor: "#059669",
    accentBg: "#ecfdf5",
    accentBorder: "#a7f3d0",
    badgeBg: "#d1fae5",
    badgeFg: "#065f46",
    summary: "不做前测，直接进入新知讲授与即时随堂巩固。",
    suitableFor: "第一次接触本课知识点、或需要系统重新学习概念定理的同学。",
    estimatedDuration: "20 - 30 分钟",
    hasPreAssessment: false,
    preAssessmentLabel: "无需前测",
    practicePolicy: "边学边练 · 阶梯式题组",
    steps: [
      {
        index: 1,
        title: "学习新知",
        description: "概念微课与图文精讲，深度拆解核心定义与几何直观。",
      },
      {
        index: 2,
        title: "随堂演练",
        description: "即学即练阶梯题组，即时对错判定与分步智能解析。",
      },
      {
        index: 3,
        title: "掌握检查",
        description: "课末掌握度小测，检验当堂吸收效果并更新知识图谱。",
      },
    ],
    highlights: [
      "零门槛直接开学，消除课前小测心理负担",
      "精讲与跟练穿插交替，注重概念深度理解与内化",
      "自动记录掌握度，课后即刻形成学习画像",
    ],
    ctaText: "以「上新课」模式进入学习",
  },
  {
    id: CLASSROOM_LEARNING_MODE.FOUNDATION,
    title: "打基础",
    englishTitle: "Build Solid Foundation",
    tag: "智能跳关 · 逐层过关",
    tagType: "blue",
    iconName: "layers",
    accentColor: "#0445fc",
    accentBg: "#eff4ff",
    accentBorder: "#bfdbfe",
    badgeBg: "#dbeafe",
    badgeFg: "#1e40af",
    summary: "先做课前测摸底学情，按认知层级逐层学习并解锁。",
    suitableFor: "已有一定了解需巩固夯实、或课后希望快速查漏补缺的同学。",
    estimatedDuration: "15 - 25 分钟",
    hasPreAssessment: true,
    preAssessmentLabel: "包含课前小测 (5-8题)",
    practicePolicy: "智能跳关 · 认知层级突破",
    steps: [
      {
        index: 1,
        title: "课前小测",
        description: "精选5-8道小题摸底已知水平，快速识别掌握与薄弱点。",
      },
      {
        index: 2,
        title: "逐层学习",
        description: "已掌握点自动跳关免学，集中精力攻克未达标难点层级。",
      },
      {
        index: 3,
        title: "解锁进阶",
        description: "层级递进闯关，稳扎稳打夯实知识底座，解锁进阶内容。",
      },
    ],
    highlights: [
      "基于掌握度判定，已懂内容免学免练，省时高效",
      "认知梯级分明，从基础定义到性质应用层层推进",
      "每通关一层即时解锁下一层，正向反馈充足",
    ],
    ctaText: "以「打基础」模式进入学习",
  },
  {
    id: CLASSROOM_LEARNING_MODE.REMEDIATION,
    title: "查缺补漏",
    englishTitle: "Targeted Remediation",
    tag: "综合诊断 · 靶向拔高",
    tagType: "amber",
    iconName: "scan-search",
    accentColor: "#d97706",
    accentBg: "#fffbeb",
    accentBorder: "#fde68a",
    badgeBg: "#fef3c7",
    badgeFg: "#92400e",
    summary: "先做单元综合测试，智能诊断弱项并逐个攻克。",
    suitableFor: "单元复习、期中/期末考前冲刺、专项疑难盲区集中消灭的同学。",
    estimatedDuration: "30 - 45 分钟",
    hasPreAssessment: true,
    preAssessmentLabel: "包含单元全卷测试",
    practicePolicy: "弱项雷达 · 靶向变式题集",
    steps: [
      {
        index: 1,
        title: "单元测试",
        description: "全卷综合测评扫描本单元全部考点，快速定位薄弱环节。",
      },
      {
        index: 2,
        title: "定位薄弱点",
        description: "系统生成弱项诊断雷达图，清晰呈现知识切片掌握度短板。",
      },
      {
        index: 3,
        title: "逐点靶向攻克",
        description: "针对错题知识点点拨微课，搭配同类变式题强化刷透。",
      },
    ],
    highlights: [
      "一键摸清整单元薄弱知识盲区，拒绝低效盲目刷题",
      "针对性微课对症下药，深入剖析典型错因与易错陷阱",
      "推送相似变式题二次检验，确保真掌握、真过关",
    ],
    ctaText: "以「查缺补漏」模式进入学习",
  },
];
