import { CLASSROOM_LEARNING_MODE } from "../../shared/domain/classroomLearningMode";

export const DETAILED_MODE_CONFIGS = [
  {
    id: CLASSROOM_LEARNING_MODE.NEW_LESSON,
    title: "学新课",
    englishTitle: "Learn New Lesson",
    tag: "首学推荐 · 循序渐进",
    tagType: "emerald",
    iconName: "new-lesson",
    kidTitle: "学新课",
    kidMotto: "直入新知 · 逐级通关",
    kidRecommendBadge: "首学推荐",
    kidDescription: "无需做课前测试，直接开学新知。跟随系统拆解步骤，边学边练、逐级通关掌握新技能。",
    kidPath: [
      { num: "1", label: "新知精讲", desc: "理解核心概念", icon: "concept" },
      { num: "2", label: "边学边练", desc: "即时随堂互动", icon: "practice" },
      { num: "3", label: "逐级通关", desc: "点亮知识掌握", icon: "milestone" },
    ],
    accentColor: "#059669",
    accentBg: "#f0fdf4",
    accentBorder: "#a7f3d0",
    cardGlow: "rgba(5, 150, 105, 0.08)",
    badgeBg: "#ecfdf5",
    badgeFg: "#047857",
    summary: "无需课前测，直接进入新知学习与即时随堂巩固，逐级通关。",
    suitableFor: "第一次接触本课新知识、或想从头系统新学一遍的同学。",
    hasPreAssessment: false,
    practicePolicy: "边学边练 · 阶梯式题组",
    steps: [
      {
        index: 1,
        title: "学习新知",
        description: "核心概念与图文精讲，深度拆解核心定义与直观逻辑。",
      },
      {
        index: 2,
        title: "随堂演练",
        description: "即学即练阶梯题组，即时对错判定与智能解题指导。",
      },
      {
        index: 3,
        title: "逐级通关",
        description: "逐关达标过关，检验当堂吸收效果并点亮知识掌握。",
      },
    ],
    highlights: [
      "无需做前测，零门槛直接开学新知识",
      "精讲与随堂练习穿插，循序渐进掌握",
      "逐级通关解锁，稳扎稳打搞懂新内容",
    ],
    ctaText: "进入「学新课」",
  },
  {
    id: CLASSROOM_LEARNING_MODE.FOUNDATION,
    title: "打基础",
    englishTitle: "Build Solid Foundation",
    tag: "课后巩固 · 智能跳关",
    tagType: "blue",
    iconName: "foundation",
    kidTitle: "打基础",
    kidMotto: "课后巩固 · 练透精熟",
    kidRecommendBadge: "巩固精熟",
    kidDescription: "适合课后巩固复习。先做摸底测试，已学会的自动跳过，只练不熟的知识点，答对达标直至彻底精熟。",
    kidPath: [
      { num: "1", label: "学情摸底", desc: "快速识别水平", icon: "check" },
      { num: "2", label: "智能跳关", desc: "已掌握免重复", icon: "skip" },
      { num: "3", label: "巩固精熟", desc: "练透攻克薄弱", icon: "mastery" },
    ],
    accentColor: "#2563eb",
    accentBg: "#eff6ff",
    accentBorder: "#bfdbfe",
    cardGlow: "rgba(37, 99, 235, 0.08)",
    badgeBg: "#f0f7ff",
    badgeFg: "#1d4ed8",
    summary: "先做摸底测试，已掌握内容自动跳过，专攻未达标点巩固到精熟。",
    suitableFor: "已经上过课需要课后巩固、希望针对薄弱点高效练习达到精熟的同学。",
    hasPreAssessment: true,
    practicePolicy: "智能跳关 · 认知层级巩固",
    steps: [
      {
        index: 1,
        title: "学情摸底",
        description: "精选题组摸底已知水平，快速识别已掌握与薄弱知识点。",
      },
      {
        index: 2,
        title: "智能跳关",
        description: "已掌握点自动跳过免做，集中精力攻克未达标巩固项。",
      },
      {
        index: 3,
        title: "精熟达标",
        description: "针对薄弱点逐步推进练习，直至知识点全部达到精熟。",
      },
    ],
    highlights: [
      "会做的题目自动跳过，不重复做无用功",
      "专攻未达标薄弱点，课后巩固针对性强",
      "练习直到答对达标，确保知识点真正精熟",
    ],
    ctaText: "进入「打基础」",
  },
  {
    id: CLASSROOM_LEARNING_MODE.REMEDIATION,
    title: "查缺补漏",
    englishTitle: "Targeted Remediation",
    tag: "单元诊断 · 靶向精熟",
    tagType: "amber",
    iconName: "remediation",
    kidTitle: "查缺补漏",
    kidMotto: "单元诊断 · 高效精熟",
    kidRecommendBadge: "高效突破",
    kidDescription: "先做单元综合测试，智能诊断找出薄弱点，在有限时间内针对薄弱点挨个攻克做到精熟，实现最高效学习。",
    kidPath: [
      { num: "1", label: "单元测试", desc: "全卷综合诊断", icon: "diagnostic" },
      { num: "2", label: "定位薄弱点", desc: "智能锁定短板", icon: "locate" },
      { num: "3", label: "靶向精熟", desc: "逐个攻克达精熟", icon: "target-mastery" },
    ],
    accentColor: "#d97706",
    accentBg: "#fffbeb",
    accentBorder: "#fde68a",
    cardGlow: "rgba(217, 119, 6, 0.08)",
    badgeBg: "#fefce8",
    badgeFg: "#b45309",
    summary: "先做单元综合测试定位薄弱点，有限时间内针对薄弱点挨个做到精熟。",
    suitableFor: "单元复习、考前冲刺、需要在有限时间内快速消灭薄弱项实现高效学习的同学。",
    hasPreAssessment: true,
    practicePolicy: "弱项诊断 · 靶向高效攻克",
    steps: [
      {
        index: 1,
        title: "单元测试",
        description: "综合测评全方位诊断本单元考点，快速定位薄弱环节。",
      },
      {
        index: 2,
        title: "定位薄弱点",
        description: "智能分析测试结果，清晰锁定各个薄弱知识点清单。",
      },
      {
        index: 3,
        title: "靶向精熟",
        description: "在有限时间内针对薄弱点挨个定向攻克，全面达到精熟。",
      },
    ],
    highlights: [
      "单元综合体检，快速诊断所有薄弱盲区",
      "有限时间内集中火力，不做无针对性的刷题",
      "薄弱点逐个攻破，解法相同、场景不同，高效达精熟",
    ],
    ctaText: "进入「查缺补漏」",
  },
];

